#!/usr/bin/env bash
# Install and configure HAProxy
apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

config=\
"
frontend myfrontend
	bind *:80
	mode http
	default_backend myservers
backend myservers
	balance roundrobin
	server 1958-web-01 3.236.228.47:80 check
	server 1958-web-02 18.206.81.165:80 check
"
echo "$config" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
