#!/usr/bin/env bash
# Script that installs and configures HAproxy load balancer on my lb-01 server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy=2.5.\*
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

config=\
"
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon
defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
backend myservers
	balance roundrobin
	server 1958-web-01 3.229.134.247:80 check
	server 1958-web-02 18.210.27.60:80 check
frontend myfrontend
	bind :80
	mode http
	default_backend myservers
"

echo "$config" > /etc/haproxy/haproxy.cfg

sudo service haproxy restart
