#!/usr/bin/env bash
#what type of network connects a computer in local
#what type of network connects office building to another office
#in a building a few streets away
#what network do you use to browse www.google.com from smartphone
#(not connected to wifi)
3

2

3

